OPTS=-dpi 150 -res 0.2 -png

all: 1.png 2.png 3.png 4.png 5.png 6.png 7.png 8.png 9.png 10.png 11.png \
12.png 13.png 14.png

1.png: 1.tex
	textogif $(OPTS) $<

2.png: 2.tex
	textogif $(OPTS) $<

3.png: 3.tex
	textogif $(OPTS) $<

4.png: 4.tex
	textogif $(OPTS) $<

5.png: 5.tex
	textogif $(OPTS) $<

6.png: 6.tex
	textogif $(OPTS) $<

7.png: 7.tex
	textogif $(OPTS) $<

8.png: 8.tex
	textogif $(OPTS) $<

9.png: 9.tex
	textogif $(OPTS) $<

10.png: 10.tex
	textogif $(OPTS) $<
	
11.png: 11.tex
	textogif $(OPTS) $<

12.png: 12.tex
	textogif $(OPTS) $<
	
13.png: 13.tex
	textogif $(OPTS) $<

14.png: 14.tex
	textogif $(OPTS) $<


clean: cleansome
	rm -f *.png

cleansome:
	rm -f *.gif *.ps
